version: "3.8"

services:
  nsfw_api:
    container_name: nsfw_api
    build: .
    restart: unless-stopped
    ports:
      - "5002:8000"
    entrypoint: sh /app/entrypoint.sh
    volumes:
      - .:/app
